const _data = [
  {name: '190613_1.jpg', artist: 'Joan Mitchell', city: 'New York', location: 'David Zwirner'},
  {name: '190613_2.jpg', artist: 'Desert Painters of Australia', city: 'New York', location: 'Gagosian'},
  {name: '190613_3.jpg', artist: 'Jesús Rafael Soto', city: 'New York', location: 'Hauser & Wirth'},
  {name: '190613_4.jpg', artist: 'Joan Mitchell', city: 'New York', location: 'David Zwirner'},
  {name: '190613_5.jpg', artist: 'Jonas Wood', city: 'New York', location: 'Gagosian'},
  {name: '190613_6.jpg', artist: 'Desert Painters of Australia', city: 'New York', location: 'Gagosian'},
  {name: '190613_7.jpg', artist: 'Desert Painters of Australia', city: 'New York', location: 'Gagosian'},
  {name: '190613_8.jpg', artist: 'Desert Painters of Australia', city: 'New York', location: 'Gagosian'},
  {name: '190613_9.jpg', artist: 'Desert Painters of Australia', city: 'New York', location: 'Gagosian'},
  {name: '190613_10.jpg', artist: 'Sanya Kantarovsky', city: 'New York', location: 'Luhring Augustine'},
  {name: '190613_11.jpg', artist: 'Desert Painters of Australia', city: 'New York', location: 'Gagosian'},
  {name: '190613_12.jpg', artist: 'Desert Painters of Australia', city: 'New York', location: 'Gagosian'},
  {name: '190505_1.jpg', artist: 'Isabella Kirkland', city: 'San Francisco', location: 'Marinship Studios'},
  {name: '190607_1.jpg', artist: 'Andy Warhol', city: 'San Francisco', location: 'SF MOMA'},
  {name: '190607_2.jpg', artist: 'Andy Warhol', city: 'San Francisco', location: 'SF MOMA'},
  {name: '190608_1.jpg', artist: 'Samuel Miller', city: 'San Francisco', location: 'De Young'},
  {name: '190502_1.jpg', artist: 'Tung Chiang', city: 'San Francisco', location: 'Heath Studio'},
  {name: '190502_2.jpg', artist: 'Tung Chiang', city: 'San Francisco', location: 'Heath Studio'},
  {name: '190616_1.jpg', artist: 'Paul Rand', city: 'New York', location: 'Cooper Hewitt Design Museum'},
  {name: '181123_1.jpg', artist: 'Radim Pesko', city: 'Taipei', location: 'Not Just Library'},
  {name: '180901_1.jpg', artist: 'Selgascano', city: 'Bruges', location: 'Pavilion'},
  {name: '180902_2.jpg', artist: '', city: 'Ghent', location: 'Design Museum Gent'},
  {name: '180831_1.jpg', artist: 'Pieter Bruegel', city: 'Belgium', location: 'Royal Museums of Fine Arts'},
  {name: '181212_1.jpg', artist: 'Fan Ho', city: 'San Francisco', location: 'Minnesota Street Project'},
  {name: '180823_1.jpg', artist: '', city: 'Berlin', location: 'Holocaust Memorial'},
  {name: '180816_1.jpg', artist: '', city: 'Istanbul', location: 'Topkapi Palace Museum'},
  {name: '180816_2.jpg', artist: '', city: 'Istanbul', location: 'Topkapi Palace Museum'},
  {name: '180816_3.jpg', artist: '', city: 'Istanbul', location: 'Topkapi Palace Museum'},
  {name: '180822_1.jpg', artist: 'Portia Zvavahera', city: 'Berlin', location: 'KW Institute'},
  {name: '180829_1.jpg', artist: 'Mario Pfeifer', city: 'Berlin', location: 'Academy of Arts'},
  {name: '180826_1.jpg', artist: '', city: 'Berlin', location: 'Berlinische Galerie'},
  {name: '180815_1.jpg', artist: 'Cem Dinlenmiş', city: 'Istanbul', location: 'Jeff Talks'},
  {name: '180729_1.jpg', artist: 'Ahn Sang-Soo', city: 'Taipei', location: 'Xue Xue Gallery'},
  {name: '180729_2.jpg', artist: 'Ahn Sang-Soo', city: 'Taipei', location: 'Xue Xue Gallery'}
];
